name: "Reusable Workflow Parser Issue"
on:
  push:
  workflow_dispatch:

jobs:
  test:
    # expected to skip, since `vars.SOME_VALUE` is not defined
    if: ${{ vars.SOME_VALUE }}
    uses: ./.github/workflows/print.yml
    with:
      value: ${{ vars.SOME_VALUE }}
