name: "Reusable Workflow Parser Issue"
on:
  push:
  workflow_dispatch:

jobs:
  test:
    # expected to skip, since `vars.SOME_JSON` is not defined
    if: ${{ vars.SOME_JSON }}
    uses: ./.github/workflows/print.yml
    with:
      value: ${{ fromJSON(vars.SOME_JSON) }}
